### PR TITLE
Remove versions, change default instance

### PR DESCRIPTION
**Pull request by kendaleiv**
#26

### CODE REVIEW

**Comment by kendaleiv** [comment]
@jrusbatch @khalidabuhakmeh What do you think about this?

**Comment by khalidabuhakmeh** [comment]
I didn't want you to remove the idea of versions, just remove the validation. This is a breaking change that I didn't want to make.

**Comment by kendaleiv** [comment]
What about changing the default instance? Do we want to do that (in a separate PR)?

**Comment by khalidabuhakmeh** [comment]
I'll talk to @kendaleiv offline to clarify my viewpoint.

**Pull request closed without merging**
