### PR TITLE
Target .netstandard2.0 and .Net framework 4.7.1

### PR DESCRIPTION
**Pull request by CasperWSchmidt**
Solves #45 

.Net framework 4.7.1 is needed to avoid version conflicts for System.Runtime.InteropServices. I hope this will not be a problem. build.cmd is modified according to https://github.com/ritterim/automation-storage-emulator/pull/19

Registry-lookup is only done for Windows machines.

### CODE REVIEW

**Comment by kendaleiv** [comment]
Thanks for the contribution! However, AppVeyor isn't seeing any artifacts when building this pull request currently. Also, we'll want to set the version to `1.0.0` as a major version bump since the minimum framework requirements are changing.

**Comment by CasperWSchmidt** [comment]
Hi @kendaleiv 
I have bumped the version to 1.0.0. As for AppVeyor I don't know how that works. I have only changed the build script to do some extra stuff (exact copy of the storage-emulator-project you refered to in #45

**Comment by kendaleiv** [comment]
AppVeyor will capture any `.nupkg` file in the `artifacts` folder for publish to NuGet. So we just need it to publish a package to the `artifacts` folder. https://github.com/ritterim/automation-sql/blob/df88aa59d71a57cfbd7a51aa025a1baaa72c8a20/appveyor.yml#L20-L22

**Comment by kendaleiv** [comment]
If you want to do it, great! Otherwise, let me know and I'll take over from here. Thanks for your help!

**Comment by kendaleiv** [comment]
OK, sure! I'll merge this in and get the artifact publishing in another PR. Thanks for your contribution!

**Comment by CasperWSchmidt** [comment]
No problem.
Have you thought about my suggestion to throw an error in the constructor when not running on windows?

**Comment by kendaleiv** [comment]
I didn't consider that but if you think it's a good idea feel free to submit a PR. It might be better to throw from a method, rather than the constructor, though.

**Comment by kendaleiv** [comment]
Released in https://www.nuget.org/packages/RimDev.Automation.Sql/1.0.0

**Pull request merged**
