### PR TITLE
Allow installing LocalDb instance automatically if it is not installe…

### PR DESCRIPTION
**Pull request by CasperWSchmidt**
…d already. Default is false.

I have used the same code in my local Database-tools package (using this awesome package with DbUp to perform both integration testing and database migration).

By having a default value of false it is a non-breaking change but it allows others to avoid the problems with running a cmd.exe command before the tests.

Sorry for not including any tests. I'm not sure which tests could make sense here...

### CODE REVIEW

**Comment by Sobieck** [comment]
Would this require you to run as an admin?

**Comment by CasperWSchmidt** [comment]
As far as I remember my cmd window was not running in as administrator when
I installed v13.0 locally and the code does the same thing as running the
command from cmd.
Are the commands running as administrator on the build server?
I will try to remember to check it out tomorrow

man. 26. nov. 2018 21.41 skrev Thomas Sobieck <notifications@github.com>:

**Comment by kendaleiv** [comment]
I think the build server (AppVeyor) runs with Administrator privileges.

**Comment by CasperWSchmidt** [comment]
I have checked. I can run sqllocaldb commands in cmd without "open as administrator" - including stopping/deleting instances. Also, running Visual Studio without "open as administrator" a test I wrote successfully creates a new instance on my machine.

btw. This feature makes me realize that the property Version (along with the constructor parameter version) is misleading since it is really an instance name and not a version number.
I don't know if this should be change (and perhaps a new Version property/parameter introduces for the instance creation) as part of this PR or not since it probably would be considered a breaking change...

**Comment by kendaleiv** [comment]
If you want to add support for customizing the instance name that's cool, but we've just been in the habit of just what the commands in README.md provide.

**Comment by kendaleiv** [comment]
Thanks for the contribution!

**Pull request merged**
